stages:
  - test
  - deploy
  - test

services:
  - postgres:latest

test:
  stage: test
  image: elixir:1.8.1-alpine
  script:
  - apk --update add postgresql-client git make g++
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix test --trace
  variables:
    POSTGRES_DATABASE: boruta_test
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    MIX_ENV: test

deploy:
  stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=boruta --api-key=$HEROKU_API_KEY
  only:
  - master

