---
configuration:
  gateway:
    - authorize: false
      error_content_type: "text/plain"
      forbidden_response: "forbidden"
      unauthorized_response: "unauthorized"
      forwarded_token_secret: "this is a secret"
      forwarded_token_signature_alg: "HS512"
      pool_count: 1
      pool_size: 10
      max_idle_time: 10
      scheme: "http"
      host: "httpbin-sidecar"
      port: 8083
      uris: ["/httpbin"]
      strip_uri: true
    - authorize: false
      error_content_type: "text/plain"
      forbidden_response: "forbidden"
      unauthorized_response: "unauthorized"
      forwarded_token_secret: "this is a secret"
      forwarded_token_signature_alg: "HS512"
      pool_count: 1
      pool_size: 10
      max_idle_time: 10
      scheme: "http"
      host: "protected-httpbin-sidecar"
      port: 8083
      uris: ["/protected-httpbin"]
      strip_uri: true
