- hosts: localhost
  tasks:
    - name: Add stable bitnami repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Add stable jetstack repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    - name: Create a k8s namespace
      kubernetes.core.k8s:
        api_version: v1
        name: boruta-staging
        kind: Namespace
        state: present

    - name: Install cert-manager helm package
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        chart_version: 1.8.0
        release_namespace: cert-manager
        create_namespace: true
        values:
          installCRDs: true

    - name: Install postgres helm package
      kubernetes.core.helm:
        name: postgres
        chart_ref: bitnami/postgresql
        chart_version: 10.16.2
        release_namespace: boruta-staging
        values:
          global.postgresql.postgresqlPassword	: "{{ postgresql_password }}"
          postgresqlMaxConnections: "200"

    - name: Create libcluster role
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: libcluster-role
            namespace: boruta-staging
          rules:
          - apiGroups: [""]
            resources: ["pods"]
            verbs: ["get", "list", "watch"]

    - name: Create libcluster binding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: libcluster-bindings
            namespace: boruta-staging
          subjects:
          - kind: ServiceAccount
            name: default
            namespace: boruta-staging
          roleRef:
            kind: Role
            name: libcluster-role
            apiGroup: rbac.authorization.k8s.io

    - name: Create SSL let's encrypt certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt-production
          spec:
            acme:
              email: io.pascal.knoth@gmail.com
              server: https://acme-v02.api.letsencrypt.org/directory
              privateKeySecretRef:
                name: boruta-staging-ssl-account-key
              solvers:
              - http01:
                  ingress:
                    class: nginx
                selector:
                  dnsZones:
                  - 'boruta.patatoid.fr'

    - name: Create Boruta Ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: main-ingress
            namespace: boruta-staging
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: letsencrypt-production
            #   nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
            - host: "{{ gateway_host }}"
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: boruta-gateway
                      port:
                        number: 4000
            - host: "{{ oauth_host }}"
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: boruta-oauth
                      port:
                        number: 4001
            - host: "{{ admin_host }}"
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: boruta-admin
                      port:
                        number: 4002
            tls:
              - hosts:
                - "{{ oauth_host }}"
                - "{{ admin_host }}"
                - "{{ gateway_host }}"
                secretName: boruta-staging-cert

    - name: create boruta app ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: boruta-env
            namespace: boruta-staging
          data:
            SECRET_KEY_BASE: fm6UIOyjYUe51Xo7JDTurwSeyOoZ15Kmlbj4NUhU9951P8cEUZc3k8bsAeJJtCvg
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: "{{ postgresql_password }}"
            POSTGRES_DATABASE: boruta
            POSTGRES_HOST: postgres-postgresql
            MAX_LOG_RETENTION_DAYS: "5"
            K8S_NAMESPACE: boruta-staging
            K8S_SELECTOR: app=boruta
            BORUTA_ADMIN_OAUTH_CLIENT_ID: "{{ admin_client_id }}"
            BORUTA_ADMIN_OAUTH_CLIENT_SECRET: "{{ admin_client_secret }}"
            BORUTA_ADMIN_OAUTH_BASE_URL: "{{ oauth_base_url }}"
            BORUTA_ADMIN_EMAIL: "{{ admin_email }}"
            BORUTA_ADMIN_PASSWORD: "{{ admin_password }}"
            BORUTA_ADMIN_HOST: "{{ admin_host }}"
            BORUTA_ADMIN_PORT: "4002"
            BORUTA_ADMIN_BASE_URL: "{{ boruta_base_url }}"
            BORUTA_ADMIN_BASE_SOCKET_URL: "{{ vue_app_boruta_base_socket_url }}"
            BORUTA_OAUTH_HOST: "{{ oauth_host }}"
            BORUTA_OAUTH_PORT: "4001"
            BORUTA_OAUTH_BASE_URL: "{{ oauth_base_url }}"
            BORUTA_GATEWAY_PORT: "4000"
            MAILJET_API_KEY: "{{ mailjet_api_key }}"
            MAILJET_SECRET: "{{ mailjet_secret }}"
            POOL_SIZE: "10"

    - name: Setup boruta database
      register: database_setup
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: boruta-setup
            namespace: boruta-staging
          backoffLimit: 3
          spec:
            template:
              spec:
                containers:
                  - image: registry.gitlab.com/patatoid/boruta/app:latest
                    command: ["/app/bin/boruta"]
                    args: ["eval", "Boruta.Release.setup"]
                    envFrom:
                    - configMapRef:
                        name: boruta-env
                    imagePullPolicy: Always
                    name: boruta
                restartPolicy: OnFailure
                imagePullSecrets:
                - name: regcred

    - name: Migrate boruta database
      when: not database_setup.changed
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: "boruta-migration-{{ release_tag }}"
            namespace: boruta-staging
          backoffLimit: 3
          spec:
            ttlSecondsAfterFinished: 864000
            template:
              spec:
                containers:
                  - image: "registry.gitlab.com/patatoid/boruta/app:{{ release_tag }}"
                    command: ["/app/bin/boruta"]
                    args: ["eval", "Boruta.Release.migrate"]
                    envFrom:
                    - configMapRef:
                        name: boruta-env
                    imagePullPolicy: Always
                    name: boruta
                restartPolicy: OnFailure
                imagePullSecrets:
                - name: regcred

    - name: Create Boruta logs storage class
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: boruta-logs
          provisioner: csi.scaleway.com

    - name: Create Boruta logs persistent volume claim
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: boruta-logs-pvc
            namespace: boruta-staging
          spec:
            storageClassName: boruta-logs
            accessModes:
              - ReadWriteOnce # TODO will cause issues when running on multiple nodes
            resources:
              requests:
                storage: 1Gi

    - name: Get blue/green deployment status
      kubernetes.core.k8s_info:
        kind: Service
        namespace: boruta-staging
        label_selectors:
          - "app=boruta"
      register: boruta_services

    - name: Create Boruta blue/green deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ 'boruta-green' if boruta_services.resources[0].spec.selector.app == 'boruta-blue' else 'boruta-blue' }}"
            namespace: boruta-staging
          spec:
            replicas: 2
            strategy:
              type: Recreate
              rollingUpdate: null
            selector:
              matchLabels:
                app: "{{ 'boruta-green' if boruta_services.resources[0].spec.selector.app == 'boruta-blue' else 'boruta-blue' }}"
            template:
              metadata:
                name: boruta
                labels:
                  app: "{{ 'boruta-green' if boruta_services.resources[0].spec.selector.app == 'boruta-blue' else 'boruta-blue' }}"
              spec:
                volumes:
                  - name: logs
                    persistentVolumeClaim:
                      claimName: boruta-logs-pvc
                containers:
                  - image: "registry.gitlab.com/patatoid/boruta/app:{{ release_tag }}"
                    readinessProbe:
                      httpGet:
                        path: /healthcheck
                        port: 4001
                    envFrom:
                      - configMapRef:
                          name: boruta-env
                    imagePullPolicy: Always
                    name: boruta
                    volumeMounts:
                      - mountPath: "/app/log"
                        name: logs
                imagePullSecrets:
                - name: regcred

    - name: Wait for deployment readyness
      shell: "kubectl -n boruta-staging wait --for=condition=Ready po --all -l app={{ 'boruta-green' if boruta_services.resources[0].spec.selector.app == 'boruta-blue' else 'boruta-blue' }}"
      retries: 6
      delay: 5
      register: result
      until: result.rc == 0

    - name: Create OAuth Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: boruta-oauth
            namespace: boruta-staging
            labels:
              app: boruta
          spec:
            selector:
              app: "{{ 'boruta-green' if boruta_services.resources[0].spec.selector.app == 'boruta-blue' else 'boruta-blue' }}"
            ports:
            - protocol: TCP
              targetPort: 4001
              name: oauth-tcp
              port: 4001

    - name: Create Admin Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: boruta-admin
            namespace: boruta-staging
            labels:
              app: boruta
          spec:
            selector:
              app: "{{ 'boruta-green' if boruta_services.resources[0].spec.selector.app == 'boruta-blue' else 'boruta-blue' }}"
            ports:
            - protocol: TCP
              targetPort: 4002
              name: admin-tcp
              port: 4002

    - name: Create Gateway Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: boruta-gateway
            namespace: boruta-staging
            labels:
              app: boruta
          spec:
            selector:
              app: "{{ 'boruta-green' if boruta_services.resources[0].spec.selector.app == 'boruta-blue' else 'boruta-blue' }}"
            ports:
            - protocol: TCP
              targetPort: 4000
              name: gateway-tcp
              port: 4000

    - name: Delete Boruta blue/green deployment
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ 'boruta-blue' if boruta_services.resources[0].spec.selector.app == 'boruta-blue' else 'boruta-green' }}"
            namespace: boruta-staging
